# @Author: cole
# @Date:   2018-10-18T21:58:57-04:00
# @Filename: main.yml
# @Last modified by:   cole
# @Last modified time: 2018-11-10T12:57:27-05:00



---
# tasks file for docker
- import_tasks: docker_centos.yml
  when: ansible_distribution == 'CentOS'

- import_tasks: docker_fedora.yml
  when: ansible_distribution == 'Fedora'
